import { Box, Container, Text } from "@chakra-ui/react";

export function CountryInfo() {
    return (
        <Box
        width={490}
        >
            <Container
            display="flex"
            >
                <Container
                alignItems="center"
                >
                    <Text
                    fontSize={50}
                    textAlign="center"
                    color="#FFBA08"
                    fontWeight={500}
                    >
                        50
                    </Text>
                    <Text
                    fontSize={22}
                    textAlign="center"
                    fontWeight={500}
                    >
                        países
                    </Text>
                </Container>
                <Container
                alignItems="center"
                >
                    <Text
                    fontSize={50}
                    textAlign="center"
                    color="#FFBA08"
                    fontWeight={500}
                    >
                        60
                    </Text>
                    <Text
                    fontSize={22}
                    textAlign="center"
                    fontWeight={500}
                    >
                        línguas
                    </Text>
                </Container>
                <Container
                alignItems="center"
                
                >
                    <Text
                    fontSize={50}
                    textAlign="center"
                    color="#FFBA08"
                    width={145}
                    fontWeight={500}
                    >
                        27
                    </Text>
                    <Text
                    fontSize={22}
                    textAlign="center"
                    fontWeight={500}
                    width={145}
                    >
                        cidades +100
                    </Text>
                </Container>
            </Container>
        </Box>
    )
}